version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        healthcheck:
            test: ["CMD", "curl","-f","http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - rabbitmqadapter

    myapp:
        build: .
        restart: always
        container_name: myapp
        ports:
            - '8081:80'
        depends_on:
            rabbitmq3:
                condition: service_started
                
        networks:
            - rabbitmqadapter

    
networks:
    rabbitmqadapter:
        driver: bridge
